import { makeStyles, tokens } from "@fluentui/react-components";

/**
 * 全局样式表。集中在此便于维护。
 * 子组件之外通过 `useStyles()` 取用即可。
 */
export const useStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
  },
  body: {
    display: "grid",
    gridTemplateColumns: "260px minmax(0, 1fr)",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },

  /* ================= Sidebar ================= */
  sidebar: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    paddingTop: "16px",
    paddingInline: "8px",
    backgroundColor: tokens.colorNeutralBackground3,
  },
  brand: {
    paddingInline: "8px",
    marginBottom: "16px",
  },
  navGroupLabel: {
    paddingInline: "12px",
    paddingBlock: "6px",
    color: tokens.colorNeutralForeground3,
    fontSize: "11.5px",
    fontWeight: tokens.fontWeightSemibold,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileItem: {
    appearance: "none",
    background: "transparent",
    border: "none",
    width: "100%",
    minHeight: "36px",
    paddingInline: "12px",
    borderRadius: tokens.borderRadiusMedium,
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    color: tokens.colorNeutralForeground2,
    cursor: "pointer",
    textAlign: "left",
    "&:hover": {
      backgroundColor: tokens.colorSubtleBackgroundHover,
      color: tokens.colorNeutralForeground1,
    },
  },
  profileItemActive: {
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    boxShadow: tokens.shadow2,
  },
  profileItemBox: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
  },
  profileItemMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  profileItemTitle: {
    fontSize: "13px",
    fontWeight: tokens.fontWeightMedium,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  profileItemMeta: {
    fontSize: "11px",
    color: tokens.colorNeutralForeground3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  navTabList: {
    rowGap: "2px",
    paddingTop: "8px",
  },
  navTab: {
    height: "36px",
    borderRadius: tokens.borderRadiusMedium,
    paddingInline: "12px",
  },
  sidebarFooter: {
    marginTop: "auto",
    padding: "8px",
    display: "flex",
    flexDirection: "column",
    rowGap: "4px",
  },
  pathBtn: {
    appearance: "none",
    background: "transparent",
    border: "none",
    width: "100%",
    paddingInline: "12px",
    paddingBlock: "8px",
    borderRadius: tokens.borderRadiusMedium,
    textAlign: "left",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    color: tokens.colorNeutralForeground2,
    cursor: "pointer",
    "&:hover": {
      backgroundColor: tokens.colorSubtleBackgroundHover,
    },
  },
  pathBtnText: {
    minWidth: 0,
    flex: 1,
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: "11.5px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  /* ================= 内容区 ================= */
  content: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopLeftRadius: "8px",
    borderBottomLeftRadius: "8px",
    boxShadow: tokens.shadow4,
    margin: "8px 8px 8px 0",
  },

  dirtyBar: {
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
    paddingInline: "20px",
    paddingBlock: "10px",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    flexShrink: 0,
  },
  dirtyText: { flex: 1, minWidth: 0 },
  dirtyActions: { display: "flex", columnGap: "8px", flexShrink: 0 },

  profileHeader: {
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
    paddingInline: "36px",
    paddingTop: "20px",
    flexShrink: 0,
  },
  profileHeaderIcon: {
    width: "36px",
    height: "36px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground1,
  },
  profileHeaderText: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  profileHeaderTitle: {
    fontSize: "18px",
    fontWeight: tokens.fontWeightSemibold,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  profileHeaderMeta: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
  },

  scroll: { flex: 1, minHeight: 0, overflowY: "auto" },
  scrollInner: {
    width: "100%",
    maxWidth: "1024px",
    paddingInline: "36px",
    paddingTop: "20px",
    paddingBottom: "48px",
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
  },

  pageHeader: {
    display: "flex",
    flexDirection: "column",
    rowGap: "4px",
    marginBottom: "8px",
  },
  pageSubtitle: { color: tokens.colorNeutralForeground3 },

  groupTitle: {
    paddingInline: "4px",
    marginBottom: "4px",
    color: tokens.colorNeutralForeground1,
  },
  group: { display: "flex", flexDirection: "column", rowGap: "8px" },
  groupCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: "7px",
    overflow: "hidden",
  },

  row: {
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    minHeight: "56px",
    paddingInline: "16px",
    paddingBlock: "10px",
  },
  rowDivider: {
    height: "1px",
    backgroundColor: tokens.colorNeutralStroke3,
    marginInline: "16px",
  },
  rowIcon: {
    width: "24px",
    height: "24px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: tokens.colorNeutralForeground2,
  },
  rowMain: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    rowGap: "2px",
  },
  rowLabel: {
    fontSize: "14px",
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: "20px",
    color: tokens.colorNeutralForeground1,
  },
  rowDesc: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "16px",
  },
  rowControl: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
  },

  tagGroup: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    paddingInline: "16px",
    paddingBlock: "12px",
  },
  emptyTagHint: {
    paddingInline: "16px",
    paddingBlock: "16px",
    color: tokens.colorNeutralForeground3,
  },

  /* Hotkeys 列表行 */
  hkRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    minHeight: "64px",
    paddingInline: "16px",
    paddingBlock: "10px",
    cursor: "pointer",
    "&:hover": { backgroundColor: tokens.colorSubtleBackgroundHover },
  },
  hkLine: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    rowGap: "4px",
  },
  hkSentence: {
    display: "flex",
    alignItems: "center",
    columnGap: "6px",
    fontSize: "13.5px",
    color: tokens.colorNeutralForeground1,
    flexWrap: "wrap",
  },
  hkMuted: { color: tokens.colorNeutralForeground3 },
  hkInputPreview: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: "12px",
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground2,
    paddingInline: "6px",
    paddingBlock: "1px",
    borderRadius: "4px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    maxWidth: "260px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  hkDesc: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  hkActions: { display: "flex", columnGap: "4px", flexShrink: 0 },
  hkSearch: {
    paddingInline: "16px",
    paddingTop: "12px",
    paddingBottom: "8px",
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
  },

  causalCard: {
    border: `1px solid ${tokens.colorBrandStroke2}`,
    backgroundColor: tokens.colorBrandBackground2,
    borderRadius: "8px",
    padding: "12px 16px",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    color: tokens.colorBrandForeground1,
    fontSize: "13px",
    lineHeight: 1.5,
    flexWrap: "wrap",
  },
  causalKw: {
    fontFamily: tokens.fontFamilyMonospace,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    paddingInline: "6px",
    paddingBlock: "1px",
    borderRadius: "4px",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  causalWarn: {
    border: `1px solid ${tokens.colorPaletteYellowBorder1}`,
    backgroundColor: tokens.colorPaletteYellowBackground1,
    color: tokens.colorPaletteYellowForeground1,
  },

  liveWindow: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    paddingInline: "12px",
    paddingBlock: "10px",
    borderRadius: "7px",
    backgroundColor: tokens.colorNeutralBackground2,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    fontSize: "12.5px",
  },
  liveDot: {
    display: "inline-block",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
  },
  liveTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  countdownBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    rowGap: "12px",
    paddingBlock: "24px",
  },
  countdownNum: {
    fontSize: "56px",
    fontWeight: tokens.fontWeightBold,
    color: tokens.colorBrandForeground1,
    lineHeight: 1,
  },

  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    rowGap: "8px",
    paddingBlock: "48px",
    color: tokens.colorNeutralForeground3,
    textAlign: "center",
  },
  emptyState: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    rowGap: "12px",
    paddingInline: "36px",
    color: tokens.colorNeutralForeground3,
    textAlign: "center",
  },

  recordCard: {
    display: "flex",
    flexDirection: "column",
    rowGap: "12px",
    padding: "16px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: "7px",
    backgroundColor: tokens.colorNeutralBackground2,
  },
  recordHeader: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    flexWrap: "wrap",
  },
  recordCombo: {
    display: "flex",
    alignItems: "center",
    columnGap: "6px",
  },
  recordButton: { width: "100%" },
  recordWarn: { color: tokens.colorPaletteYellowForeground1 },
  manualToggle: {
    appearance: "none",
    background: "transparent",
    border: "none",
    color: tokens.colorBrandForegroundLink,
    cursor: "pointer",
    fontSize: "12px",
    paddingInline: "4px",
    paddingBlock: "2px",
    textAlign: "left",
    "&:hover": { textDecoration: "underline" },
  },
  manualGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
  },
  drawerForm: {
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
  },
  drawerActions: {
    display: "flex",
    justifyContent: "flex-end",
    paddingBlock: "4px",
  },
  drawerTextarea: {
    minHeight: "220px",
    fontFamily: tokens.fontFamilyMonospace,
  },

  keyChip: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "32px",
    height: "24px",
    paddingInline: "8px",
    borderRadius: "4px",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: "12px",
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: 1,
  },
  keyChipTrigger: {
    backgroundColor: tokens.colorBrandBackground2,
    border: `1px solid ${tokens.colorBrandStroke2}`,
    color: tokens.colorBrandForeground1,
  },
  keyPlus: { color: tokens.colorNeutralForeground3, fontSize: "12px" },

  windowList: {
    maxHeight: "360px",
    overflowY: "auto",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: "6px",
  },
  windowItem: {
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
    paddingInline: "12px",
    paddingBlock: "10px",
    cursor: "pointer",
    borderBottom: `1px solid ${tokens.colorNeutralStroke3}`,
    "&:hover": { backgroundColor: tokens.colorSubtleBackgroundHover },
    "&:last-child": { borderBottom: "none" },
  },
  windowItemActive: {
    backgroundColor: tokens.colorBrandBackground2,
    "&:hover": { backgroundColor: tokens.colorBrandBackground2Hover },
  },
  windowItemTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "13px",
  },
  windowPickerRow: {
    display: "flex",
    gap: "8px",
  },
  windowPickerBody: {
    display: "flex",
    flexDirection: "column",
    rowGap: "12px",
  },
});

export type AppStyles = ReturnType<typeof useStyles>;
