[package]
name = "gamemacro-daemon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gamemacro-daemon"
path = "src/main.rs"

[dependencies]
gamemacro-core = { path = "../gamemacro-core" }
enigo = { version = "0.6.1", default-features = false }
lazy_static = { version = "1.5.0", default-features = false }
notify = "8.2.0"
rdev = { version = "0.5.2", default-features = false }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "sync", "time", "macros"] }
tokio-util = { version = "0.7", default-features = false }
winapi = { version = "0.3.9", features = [
    "handleapi",
    "securitybaseapi",
    "processthreadsapi",
    "winnt",
] }

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
manifest = "app.manifest"
