name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: hotkeys.exe
            binary_name: hotkeys.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
          mv ./target/${{ matrix.target }}/release/${{ matrix.binary_name }} ./target/${{ matrix.target }}/release/${{ matrix.asset_name }}
      - name: Set Execute Permission
        if: matrix.os != 'windows-latest'
        run: |
          chmod +x ./target/${{ matrix.target }}/release/${{ matrix.asset_name }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./target/${{ matrix.target }}/release/${{ matrix.asset_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
